[theme]
primaryColor = "#FF6B35"
backgroundColor = "#FBF9F8"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#1B1C1C"
font = "sans serif"

[client]
showErrorDetails = false
toolbarMode = "minimal"

[server]
headless = true
enableCORS = false
enableXsrfProtection = true

[browser]
gatherUsageStats = false
